# Generated by Django 5.2.8 on 2025-11-24 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='running', max_length=20)),
                ('message', models.TextField(blank=True)),
                ('assignments_synced', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sync Log',
                'verbose_name_plural': 'Sync Logs',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canvas_api_key', models.CharField(blank=True, help_text='Canvas API Key', max_length=255)),
                ('canvas_base_url', models.URLField(default='https://keyinstitute.instructure.com/api/v1', help_text='Canvas API Base URL', max_length=255)),
                ('use_default_canvas_url', models.BooleanField(default=True)),
                ('notion_api_key', models.CharField(blank=True, help_text='Notion API Key', max_length=255)),
                ('notion_database_id', models.CharField(blank=True, help_text='Notion Database ID (32 char hex)', max_length=32)),
                ('selected_course_ids', models.JSONField(blank=True, default=list, help_text='List of selected Canvas course IDs')),
                ('sync_buckets', models.JSONField(blank=True, default=list, help_text='Canvas assignment buckets to sync (past, undated, upcoming, future, ungraded)')),
                ('sync_time', models.TimeField(blank=True, help_text='Scheduled daily sync time', null=True)),
                ('first_sync_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
