# Generated by Django 5.2.8 on 2025-11-24 19:35

import sync.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sync', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='notion_database_id',
            field=models.CharField(blank=True, help_text='Notion Database ID (32 char hex)', max_length=32, validators=[sync.models.validate_notion_db_id]),
        ),
    ]
